spring.application.name=login
spring.datasource.url=jdbc:postgresql://localhost:5432/arc_database
spring.datasource.username=postgres
spring.datasource.password=roopa1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b240ce4d98939c36d07d173bc70dc5d73b06bc917823e597c555fb1cd7fdf41a6652ed9a01e389e7c5b367fc9b6574218a
jwt.expiration=86400000

server.port=8080
